name: Build Flet Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
      options: --user root

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fix directory permissions and cache
      run: |
        git config --global --add safe.directory /__w/Tam/Tam
        mkdir -p /github/home/.cache/pip
        chmod -R 777 /github/home/.cache

    - name: Build APK with Buildozer
      run: |
        echo "y" | buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: |
          bin/*.apk
          *.apk
          **/*.apk
